### PR TITLE
fix the known-local ULA definitions to clarify known-local and not general ULA

### PR DESCRIPTION
**Pull request by buraglio**
Lorenzo pointed out that the ULA over IPv4 was vague, and dod not clarify known-local.

### CODE REVIEW

**Comment by buraglio** [comment]
Also add end quote at the end of the 4149 reference.

**Comment by timchown** [comment]
Actually general ULAs *are* now preferred over IPv4.  So that was correct as it was.  I did query this twice to check it's what was wanted, as I was surprised that the WG had changed its mind - originally the WG didn't want general ULA to be preferred over IPv4 because of the possibility of general ULAs in public DNS.

**Comment by timchown** [comment]
OK, so NOW I understand, the PR is good, but probably we need to say more...  and up the rev to -15

**Review by timchown — COMMENTED** [review]
thumbs up.  will check again once merged.

**Comment by buraglio** [comment]
Done

**Pull request merged**
